url: https://opensuse.lt/
DefaultContentLanguage: lt
languageCode: lt
title: openSUSE.lt
description: openSUSE Linux naujienos, pagalba nuo 2002 m. spalio 25 d.
theme: mainroad
paginate: 5
#refLinksErrorLevel: WARNING    # Issue a warning instead of error when encountering invalid ref/relref
menus:
    main:
        - name: Naujienos ir pamokos
          pageRef: /
          weight: 10
        - name: Pradedantiesiems
          pageRef: /opensuse-pradedantiesiems
          weight: 20
        - name: Parsisiųsti „openSUSE“
          url: https://get.opensuse.org/lt/leap/
          weight: 30
          params:
            rel: external
            target: _blank
        - name: Parsisiųsti „Lietuką“
          url: https://lietukas.lt/gauti.html
          weight: 40
          params:
              rel: external
              target: _blank
        - name: „Diegti tuoj pat“ kolekcija
          url: https://lietukas.lt/ymp_kolekcija.html
          weight: 50
          params:
              rel: external
              target: _blank

        - name: openSUSE įvykiai
          pageRef: /opensuse-įvykiai
          parent: Naujienos ir pamokos
          weight: 10
        - name: Skelbimai
          pageRef: /skelbimai
          parent: Naujienos ir pamokos
          weight: 20
        - name: Svetainės
          pageRef: /svetainės
          parent: Naujienos ir pamokos
          weight: 30
        - name: Kitos naujienos
          pageRef: /kitos-naujienos
          parent: Naujienos ir pamokos
          weight: 40
        - name: Sistemos diegimas
          pageRef: /diegimas
          parent: Naujienos ir pamokos
          weight: 50
        - name: Programos
          pageRef: /programos
          parent: Naujienos ir pamokos
          weight: 60
        - name: Susiję su aparatine įranga
          pageRef: /geležis
          parent: Naujienos ir pamokos
          weight: 70
        - name: Nesklandumų sprendimas
          pageRef: /klaidos
          parent: Naujienos ir pamokos
          weight: 80
        - name: Internetas ir tinklas
          pageRef: /tinklas
          parent: Naujienos ir pamokos
          weight: 90
      #  - name: Saugumas
      #    pageRef: /saugumas
      #    parent: Naujienos ir pamokos
      #    weight: 100
        - name: Išvaizdos keitimas
          pageRef: /išvaizdos-keitimas
          parent: Naujienos ir pamokos
          weight: 110
        - name: Vertimas / lokalizavimas
          pageRef: /vertimas-lokalizavimas
          parent: Naujienos ir pamokos
          weight: 120
        - name: Kitos pamokos
          pageRef: /kitos-pamokos
          parent: Naujienos ir pamokos
          weight: 130

#uglyURLs: true # uncomment to use .html suffix in URLs instead of a trailing slash
markup:
    goldmark:
        renderer:
            unsafe: true # Allow HTML tags in MarkDown
        parser:
            attribute:
                block: true
params:
    description: openSUSE Linux naujienos, pagalba nuo 2002 m. spalio 25 d.
    subtitle: openSUSE Linux naujienos, pagalba nuo 2002 m. spalio 25 d.
    copyright: opensuse.lt
    sidebar:
        home: right
        list: right
        single: right
        widgets:
            #- search
            - counter
            - laukiame-straipsnelių
    widgets:
        search:
            cached: true
            url: https://duckduckgo.com/
            input:
                name: sites
        counter:
            cached: true
        laukiame-straipsnelių:
            cached: true
    mainSections:
        - kita
        - opensuse-įvykiai
        - skelbimai
        - svetainės
    dateFormat: :date_long
    post_meta:
        - author
        - date
        - categories
        - translations
    logo:
        image: '/images/girl.png'
    customCss: [ 'css/custom.css' ]
    style:
        vars:
            highlightColor: "#0d8726"
