url: https://opensuse.lt/
DefaultContentLanguage: lt
languageCode: lt
title: openSUSE.lt
description: openSUSE Linux naujienos, pagalba nuo 2002 m. spalio 25 d.
theme: mainroad
paginate: 3
#refLinksErrorLevel: WARNING    # Issue a warning instead of error when encountering invalid ref/relref
menus:
    main:
        - name: Naujienos
          pageRef: /
          weight: 10
        - name: Pamokos
          url: /pamokos
          weight: 20
        - name: Parsisiųsti „openSUSE“
          url: https://software.opensuse.org/?locale=lt
          weight: 30
          params:
            rel: external
            target: _blank
        - name: Parsisiųsti „Lietuką“
          url: http://lietukas.lt/gauti.html
          weight: 40
          params:
              rel: external
              target: _blank
        - name: „openSUSE“ pradedantiesiems
          pageRef: /opensuse-pradedantiesiems
          weight: 50
        - name: „Diegti tuoj pat“ kolekcija
          url: http://lietukas.lt/ymp_kolekcija.html
          weight: 60
          params:
              rel: external
              target: _blank

        - name: openSUSE įvykiai
          pageRef: /opensuse-įvykiai
          parent: Naujienos
          weight: 10
        - name: Skelbimai
          pageRef: /skelbimai
          parent: Naujienos
          weight: 20
        - name: Svetainės
          pageRef: /svetainės
          parent: Naujienos
          weight: 30
        - name: Kita
          pageRef: /kita
          parent: Naujienos
          weight: 40

        - name: Sistemos diegimas
          pageRef: /pamokos/diegimas
          parent: Pamokos
          weight: 10
        - name: Programos
          pageRef: /pamokos/programos
          parent: Pamokos
          weight: 20
        - name: Susiję su aparatine įranga
          pageRef: /pamokos/geležis
          parent: Pamokos
          weight: 30
        - name: Nesklandumų sprendimas
          pageRef: /pamokos/klaidos
          parent: Pamokos
          weight: 40
        - name: Internetas ir tinklas
          pageRef: /pamokos/http
          parent: Pamokos
          weight: 50
        - name: Saugumas
          pageRef: /pamokos/saugumas
          parent: Pamokos
          weight: 60
        - name: Išvaizdos keitimas
          pageRef: /pamokos/isvaizdos-keitimas
          parent: Pamokos
          weight: 70
        - name: Įvairios pamokos
          pageRef: /pamokos/ivairus
          parent: Pamokos
          weight: 80
        - name: Vertimas / lokalizavimas
          pageRef: /pamokos/vertimas-lokalizavimas
          parent: Pamokos
          weight: 90

#uglyURLs: true # uncomment to use .html suffix in URLs instead of a trailing slash
markup:
    goldmark:
        renderer:
            unsafe: true # Allow HTML tags in MarkDown
        parser:
            attribute:
                block: true
params:
    description: openSUSE Linux naujienos, pagalba nuo 2002 m. spalio 25 d.
    subtitle: openSUSE Linux naujienos, pagalba nuo 2002 m. spalio 25 d.
    copyright: opensuse.lt
    sidebar:
        home: right
        list: right
        single: right
        widgets:
            - search
            - counter
            - laukiame-straipsnelių
    widgets:
        search:
            cached: true
            url: https://duckduckgo.com/
            input:
                name: sites
        counter:
            cached: true
        laukiame-straipsnelių:
            cached: true
    mainSections:
        - kita
        - opensuse-įvykiai
        - skelbimai
        - svetainės
    dateFormat: :date_long
    post_meta:
        - author
        - date
        - categories
        - translations
    logo:
        image: '/images/girl.png'
    customCss: [ 'css/custom.css' ]
    style:
        vars:
            highlightColor: "#0d8726"
